# Generated by Django 4.2.5 on 2023-10-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_name_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.TextField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
