# Generated by Django 4.2.5 on 2023-10-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_alter_message_options_alter_message_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='name',
        ),
    ]
